// Generated by Assets/Hananoki/CustomProjectBrowser/Editor/Localize/ja-JP.csv
namespace Hananoki.CustomProjectBrowser {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _ShowExtension => L.Tr( "Show Extension" );
		public static string _DuplicateAsset => L.Tr( "Duplicate Asset" );
		public static string _Clickontheextensiontorunitinthefiler => L.Tr( "Click on the extension to run it in the filer" );
		public static string _EnablingAddressablesupport => L.Tr( "Enabling Addressable support" );
		public static string _AddtoAddressable => L.Tr( "Add to Addressable" );
	}
}
