// Generated by Assets/Hananoki/CustomProjectBrowser/Localize/en-US.csv

namespace Hananoki.CustomProjectBrowser {
	public static class L {
		public static string Tr( int n ) {
			try {
				return EditorLocalize.GetPakage( Package.name ).m_Strings[ n ];
			}
			catch( System.Exception ) {
			}
			return string.Empty;
		}
	}
	public static class S {
		public static string _ShowExtension => L.Tr( 0 );
		public static string _DuplicateAsset => L.Tr( 1 );
		public static string _Clickontheextensiontorunitinthefiler => L.Tr( 2 );
		public static string _EnablingAddressablesupport => L.Tr( 3 );
		public static string _AddtoAddressable => L.Tr( 4 );
	}

#if UNITY_EDITOR
  [EditorLocalizeClass]
  public class LocalizeEvent {
    [EditorLocalizeMethod]
    public static void Changed() {
			EditorLocalize.Load( Package.name, "6488b518303641d44811f8850e0540e8" );
		}
	}
#endif
}
